{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "jp-spa-react.serviceAccountName" . }}
  labels:
{{ include "jp-spa-react.labels" . | nindent 4 }}
{{- end -}}
